### ISSUE TITLE
TMSU ebuild

### ISSUE THREAD

**Issue by TheChymera** [csmk/frabjous#76]
Hi @csmk, I am the (proxy) maintainer of the `sys-fs/tmsu` ebuild on the main Gentoo tree. Someone [recently](https://bugs.gentoo.org/637180#c0) pointed out [your ebuild](https://github.com/csmk/frabjous/blob/master/sys-fs/tmsu/tmsu-0.7.0.ebuild) to me, and I notice that it looks quite a bit more involved than mine.
Sadly, my knowledge about GO does not allow me to even decide if your ebuild is better suited for the main tree than mine. Particularly the `EGO_VENDOR` bit looks fairly dynamic, so I am not sure whether I should include it.

I am wondering whether you:

* could tell me what the `EGO_VENDOR` bit is good for? (I have not been able to find comprehensive [docs](https://devmanual.gentoo.org/eclass-reference/golang-vcs-snapshot.eclass/index.html) on the variable)).
* could recommend that I include your additions in the main tree?
* would be interested in taking over (proxy) maintainership of the package?

**Comment by csmk** [comment]
Hi @TheChymera!

> could tell me what the EGO_VENDOR bit is good for?

One reason is because the majority of Go packages are statically built, so instead of using the system-wide installed Go dependencies (GOROOT), I prefer to use the _[vendored](https://blog.gopheracademy.com/advent-2015/vendor-folder/)_ setup, as it gives you more control over the dependencies for each package. As a consequence, I've a more clean system. 

A second reason is because many projects are adopting the _vendored_ way, either by distributing the dependencies themselves and/or using 3rd-party package management, like Glide, Godeps, etc.

In my limited knowledge, the benefit of using GOROOT is if the package is built with `-buildmode=shared -linkshared`, but to be honest, I've not explored that _land_ yet.

> could recommend that I include your additions in the main tree?

As the Gentoo devs hasn't established a policy for Go packages, for now I think it's a matter of taste(?). So I can't claim which way is better.

> would be interested in taking over (proxy) maintainership of the package?

Only if you have lost interest in maintaining it. Otherwise, I'm happy to help you where I can. 😃

**Comment by csmk** [comment]
Resolved issue, I suppose. Please, feel free to reopen if you have any other related inquiries.
